### ISSUE TITLE
Plot disappears after updating its data for the second time in Jupiter Notebook

### ISSUE THREAD

**Issue by dhaitz** [matplotlib/matplotlib#15076]
### Bug report

Plot is created and can be updated via a widget, but disappears after the second time the object data is modified. 

To properly place the figure within a GridSpec layout, interactive mode is turned off and the figure is not created until the widget's associated function is first called.

**Code for reproduction**

```python
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np

%matplotlib widget
# or %matplotlib notebook

plt.ioff()

figures = {}

fig, ax = plt.subplots()

def update_plot(value):
    x, y = np.random.random(10), np.random.random(10)
    l = [_ for _ in zip(x, y)]
    
    if len(ax.lines) == 0:  # first call to function
        ax.plot(x,y)
        plt.show()
        
    else:  # all following calls
        ax.lines[0].set_xdata(x)
        ax.lines[0].set_ydata(y)
        fig.canvas.draw_idle()
        
my_widget = widgets.FloatSlider(min=0.1, max=0.9, step=0.1, value=0.5)

my_widget_box = widgets.interactive(update_plot, value=my_widget)
grid = widgets.GridspecLayout(2, 2, layout=widgets.Layout(justify_content='center'))
grid[0, 0] = my_widget_box

display(grid)
```

**Actual outcome**
![mpl](https://user-images.githubusercontent.com/5802753/63226720-e971e700-c1dd-11e9-9986-e53590e38b74.gif)

**Expected outcome**

Figure does not disappear 

**Matplotlib version**
  * Operating system: macOs
  * Matplotlib version: 3.1.1.
  * Matplotlib backend (`print(matplotlib.get_backend())`): "module://ipympl.backend_nbagg" (%matplotlib widget) or "nbAgg" (%matplotlib notebook)
  * Python version:  3.7.4
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: ipywidgets==7.5.1, ipympl==0.3.3, 
  * Browser: tested in Safari and Firefox

Installed via brew and pip

**Comment by timhoffm** [comment]
Likely the same cause as #15040.

**Comment by ImportanceOfBeingErnest** [comment]
Not sure. #15040 is an issue with the qt backend. However, here using `%matplotlib qt` works fine. Also the problem here does only occur when turning interactive mode off (`plt.ioff`); without it the problem also does not occur; while #15040 happens independent on the interactive mode being on or off.

**Comment by timhoffm** [comment]
Not sure about not sure :smirk:. #15040 is addressed with a change in `figure.py` (#15045, though not-yet-working). Conceptually, the cause may be the same: canvas and figure manager get out of sync.

**Comment by QuLogic** [comment]
Is this still a problem with current Matplotlib?

**Comment by mdengler** [comment]
> Is this still a problem with current Matplotlib?

I can't reproduce it, perhaps because the example code has rotted.

![image](https://user-images.githubusercontent.com/777015/115908219-df36d000-a437-11eb-9a34-07ddabf272db.png)

**Comment by dhaitz** [comment]
Hi, I just checked, code works and issue still persists on my macOS machine with Firefox.

    import sys, matplotlib, ipympl
    print(f"Python: {sys.version_info}")
    print(f"matplotlib: {matplotlib.__version__}")
    print(f"ipywidgets: {widgets.__version__}")
    print(f"ipympl: {ipympl.__version__}")

Output:

- Python: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
- matplotlib: 3.2.1
- ipywidgets: 7.5.1
- ipympl: 0.5.6

Both in matplotlib `widget` and `notebook` mode.

**Comment by QuLogic** [comment]
This is probably something related to #17576.
