### ISSUE TITLE
Bug Report: saved Figure ignores figure.facecolor

### ISSUE THREAD

**Issue by DanielGoldfarb** [matplotlib/matplotlib#17467]
### Bug report

When saving a figure, either via `plt.savefig()` or by clicking the disk icon on the figure display UI, the saved figure has no facecolor.  

**Code for reproduction**
```python
dino@DINO:~/code/mplfinance$ ipython
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import matplotlib as mpl

In [2]: mpl.__version__
Out[2]: '3.1.3'

In [3]: import matplotlib.pyplot as plt

In [4]: y = [2,4,3,7,1]
In [5]: x = [0,1,2,3,4]

In [6]: plt.rcParams['figure.facecolor'] = 'c'

In [7]: plt.plot(x,y)
Out[7]: [<matplotlib.lines.Line2D at 0x7ff9eeb49090>]

In [8]: plt.show()

In [9]: plt.rcParams['figure.facecolor'] = 'c'
In [10]: plt.plot(x,y)
Out[10]: [<matplotlib.lines.Line2D at 0x7ff9d7890d10>]

In [11]: plt.savefig('testsave.png')
```
---
### Here is what the plot looks like upon `plt.show()`

![matplotlib_fig1](https://user-images.githubusercontent.com/11164790/82488455-e9c14a80-9aad-11ea-9199-b44ea2861663.jpg)

---
### Here is what the plot looks like when I click the disk icon on the above UI to save the plot:

![matplotlib_fig1saved](https://user-images.githubusercontent.com/11164790/82488457-ea59e100-9aad-11ea-98b9-2ff0e58fa43a.jpg)

---
### Here is what the plot looks like when I call `plt.savefig('testsave.png')`

![matplotlib_testsave](https://user-images.githubusercontent.com/11164790/82488458-ea59e100-9aad-11ea-89b8-d3930ac5b8af.jpg)

**Comment by anntzer** [comment]
Almost certainly fixed by https://github.com/matplotlib/matplotlib/pull/15111 in the next release of matplotlib?

**Comment by tacaswell** [comment]
We have both `rcParams['savefig.facecolor']` and `rcParams['figure.facecolor']`.  The first get used when saving, the second get used when shown interactively.  This is a hold over from what the default background color in the GUI was a light gray but you wanted to save it with a white background.

This is partially fixed by https://github.com/matplotlib/matplotlib/pull/15111 (which at at least makes it possible mostly ignore setting the `'savefig.facecolor'`, however for supporting released versions you will need to set both.

**Comment by QuLogic** [comment]
Going to close this then, since it'll be fixed soon.

**Comment by DanielGoldfarb** [comment]
Thanks all!
Will use ` rcParams['savefig.facecolor'] ` as a workaround in the meantime.
