### ISSUE TITLE
segmentation fault when plt.show() in Mac command line

### ISSUE THREAD

**Issue by HaoyuFan-DIB** [matplotlib/matplotlib#18953]
### Bug report

Very recently I upgrade my Mac system to "Big Sur" and when I re-run my code in terminal, it crushed with "zsh: segmentation fault". This should be related to plt.show() in the end, without with everything works fine.

**Code for reproduction**

```python
# Paste your code here
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(10)
plt.plot(x,x)
plt.savefig("test.png")
plt.show()
```

**Actual outcome**

figure saved successfully but figure not displayed. The following info was given in terminal:

zsh: segmentation fault  python Figure1.py

# more information from the crush report by MacOS
Process:               python3.7 [1829]
Path:                  /Users/USER/*/python
Identifier:            python3.7
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [439]
Responsible:           Terminal [381]
User ID:               501

Date/Time:             2020-11-15 00:43:37.649 -0500
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Bridge OS Version:     5.0.1 (18P2561)
Anonymous UUID:        EE9CCA71-4EC2-E40C-A4B8-F0D8D1C7619A

Time Awake Since Boot: 3800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xffffffff00000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1829]

VM Regions Near 0xffffffff00000008:
--> unused shlib __TEXT      7fffde988000-7fffe1d0c000 [ 51.5M] r--/r-- SM=COW  system shared lib __TEXT not used by this process

**Expected outcome**

figured saved and figured displayed

**Matplotlib version**

  * Operating system: MacOS
  * Matplotlib version: 3.
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7
  * Jupyter version (if applicable):3.1.3
  * Other libraries: 

Tried to reinstall via conda using:

conda install -c conda-forge matplotlib 

did not solve the problem

**Comment by michaelStettler** [comment]
Well I got the same issue this morning when running of Friday before the update to Big Sur... 
At least cv2.imshow() still works so I am using this workaround so far

**Comment by tacaswell** [comment]
Can you try

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.use('tkagg')
x = np.arange(10)
plt.plot(x,x)
plt.savefig("test.png")
plt.show()

```

**Comment by kevinhainline** [comment]
I am getting a similar error when I try to run plt.show():

`zsh: segmentation fault  ipython`

If I run the code you provided, @tacaswell, it fails, but if I modify it slightly by placing the mpl.use() command before importing matplotlib.pyplot as plt:

`import numpy as np
import matplotlib as mpl
mpl.use('tkagg')
import matplotlib.pyplot as plt
x = np.arange(10)
plt.plot(x,x)
plt.savefig("test.png")
plt.show()`

The plot appears.

**Comment by jklymak** [comment]
@tacaswell @QuLogic is there enough $ to get a Mac mini with Big Sur on it?  Its pretty tough to upgrade one's work machine to Big Sur until Matplotlib works on it, but Matplotlib won't work on BigSur until someone upgrades their machine ;-)

**Comment by QuLogic** [comment]
I guess we could switch on MacStadium; I have no idea how it works.

**Comment by asmecca** [comment]
I had the same problem. I fixed it by updating matplotlib to the newest version

**Comment by AlexanderFalk** [comment]
I can confirm updating Matplotlib to 3.3.3 on my Macbook 16" using Big Sur fixed the issue. Plots are now shown as expected.

**Comment by tacaswell** [comment]
It looks like this is:

 - connected to OSX and bigsur
 - affects the OSX backend
 - is fixed some time between 3.1.3 and 3.3.3

This could be either due to a bug in our code that we fixed (there were a bunch of changes to the .m files) or this could be a build issue with the wheels.

@jklymak We don't have money to maintain more than one macmini, but I am on board with pushing it to the leading (instead of trailing) edge of the OSX versions we support.   If this is still a need I can try poking at it or give you access ;).

**Comment by dstansby** [comment]
👋 I'm on Big Sur now, so feel free to tag me in anything it would be good to investigate.

For this issue, I can get the `macosx` backend working fine out the box in 3.3.3 and 3.2.2, but not 3.1.3. I think that means I'll close this, with the solution to upgrade to a newer version of Matplotlib, since the 3.1.x line is no longer supported.

**Comment by chrysm** [comment]
I had this problem when upgrading to Catalina, and the only approach that worked was dropping my dpi.  None of these other suggestions helped.

**Comment by dstansby** [comment]
What version of Matplotlib did you have the problem with?

**Comment by chrysm** [comment]
3.3.3. after updating and then reinstalling my entire conda env...
turns out my figsize got set to something enormous elsewhere.  when i fixed it to something reasonable (8, 11) i got to use my 400 dpi again.

**Comment by GautamGadipudi** [comment]
> I can confirm updating Matplotlib to 3.3.3 on my Macbook 16" using Big Sur fixed the issue. Plots are now shown as expected.

Thanks @chrysm. This worked for me!

**Comment by chrysm** [comment]
everything from 3.3.1 onward including 3.3.3...

**Comment by SuperSimon81** [comment]
Im having this issue with matplotlib 3.4.2

**Comment by jklymak** [comment]
@SuperSimon81 This is closed because we don't think we can do anything about it.  If you have a new issue, please open a new report with all the appropriate information.

**Comment by SuperSimon81** [comment]
It was solved by upgrading python to 3.9.6. Feel free to close

**Comment by Shaunakde** [comment]
I noticed that I only experience this now in `ipython` and not regular python. 

Here are my library versions:
```
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.
```

```
In [2]: mpl.__version__
Out[2]: '3.5.1'
```

The error I see when I do `mpl.use('tkagg')` is:

```
In [8]: plt.plot(samples)
2022-03-15 15:02:12.391 python[60420:527701] -[NSApplication macMinorVersion]: unrecognized selector sent to instance 0x7fe42ec11b40
2022-03-15 15:02:12.396 python[60420:527701] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication macMinorVersion]: unrecognized selector sent to instance 0x7fe42ec11b40'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2048429b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201bdd92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20506ddd -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff203ec30b ___forwarding___ + 1448
	4   CoreFoundation                      0x00007fff203ebcd8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x00000001174bcdb9 SetCGColorComponents + 265
	6   libtk8.6.dylib                      0x00000001174bd67a TkpGetColor + 250
	7   libtk8.6.dylib                      0x00000001173f7aa9 Tk_GetColor + 153
	8   libtk8.6.dylib                      0x00000001173e78e6 Tk_Get3DBorder + 134
	9   libtk8.6.dylib                      0x00000001173e774f Tk_Alloc3DBorderFromObj + 127
	10  libtk8.6.dylib                      0x00000001173f8fad DoObjConfig + 941
	11  libtk8.6.dylib                      0x00000001173f8ae5 Tk_InitOptions + 357
	12  libtk8.6.dylib                      0x00000001173f89c5 Tk_InitOptions + 69
	13  libtk8.6.dylib                      0x0000000117429b5c CreateFrame + 1548
	14  libtk8.6.dylib                      0x0000000117429e37 TkListCreateFrame + 151
	15  libtk8.6.dylib                      0x00000001174217f8 Initialize + 2168
	16  _tkinter.cpython-37m-darwin.so      0x0000000117253a3f _tkinter_create + 1183
	17  python                              0x0000000100931b36 _PyMethodDef_RawFastCallKeywords + 230
	18  python                              0x0000000100a6ede2 call_function + 306
	19  python                              0x0000000100a6bb92 _PyEval_EvalFrameDefault + 42226
	20  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	21  python                              0x00000001009307c7 _PyFunction_FastCallDict + 231
	22  python                              0x00000001009b2a61 slot_tp_init + 193
	23  python                              0x00000001009bcb51 type_call + 241
	24  python                              0x00000001009314f3 _PyObject_FastCallKeywords + 179
	25  python                              0x0000000100a6ee75 call_function + 453
	26  python                              0x0000000100a6cb8d _PyEval_EvalFrameDefault + 46317
	27  python                              0x00000001009312d5 function_code_fastcall + 117
	28  python                              0x0000000100a6ed67 call_function + 183
	29  python                              0x0000000100a6bb92 _PyEval_EvalFrameDefault + 42226
	30  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	31  python                              0x00000001009307c7 _PyFunction_FastCallDict + 231
	32  python                              0x0000000100934702 method_call + 130
	33  python                              0x0000000100932172 PyObject_Call + 130
	34  python                              0x0000000100a6ccd9 _PyEval_EvalFrameDefault + 46649
	35  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	36  python                              0x00000001009307c7 _PyFunction_FastCallDict + 231
	37  python                              0x0000000100a6ccd9 _PyEval_EvalFrameDefault + 46649
	38  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	39  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	40  python                              0x0000000100a6ed67 call_function + 183
	41  python                              0x0000000100a6cad4 _PyEval_EvalFrameDefault + 46132
	42  python                              0x00000001009312d5 function_code_fastcall + 117
	43  python                              0x0000000100a6ed67 call_function + 183
	44  python                              0x0000000100a6cad4 _PyEval_EvalFrameDefault + 46132
	45  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	46  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	47  python                              0x0000000100a6ed67 call_function + 183
	48  python                              0x0000000100a6cad4 _PyEval_EvalFrameDefault + 46132
	49  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	50  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	51  python                              0x0000000100a6ed67 call_function + 183
	52  python                              0x0000000100a6bb92 _PyEval_EvalFrameDefault + 42226
	53  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	54  python                              0x0000000100a5ae9b builtin_exec + 347
	55  python                              0x0000000100931b36 _PyMethodDef_RawFastCallKeywords + 230
	56  python                              0x0000000100a6ede2 call_function + 306
	57  python                              0x0000000100a6cad4 _PyEval_EvalFrameDefault + 46132
	58  python                              0x000000010094a519 gen_send_ex + 169
	59  python                              0x0000000100a67c72 _PyEval_EvalFrameDefault + 26066
	60  python                              0x000000010094a519 gen_send_ex + 169
	61  python                              0x0000000100a67c72 _PyEval_EvalFrameDefault + 26066
	62  python                              0x000000010094a519 gen_send_ex + 169
	63  python                              0x0000000100931ad3 _PyMethodDef_RawFastCallKeywords + 131
	64  python                              0x000000010093e554 _PyMethodDescr_FastCallKeywords + 84
	65  python                              0x0000000100a6ee65 call_function + 437
	66  python                              0x0000000100a6bafc _PyEval_EvalFrameDefault + 42076
	67  python                              0x00000001009312d5 function_code_fastcall + 117
	68  python                              0x0000000100a6ed67 call_function + 183
	69  python                              0x0000000100a6cad4 _PyEval_EvalFrameDefault + 46132
	70  python                              0x00000001009312d5 function_code_fastcall + 117
	71  python                              0x0000000100a6ed67 call_function + 183
	72  python                              0x0000000100a6bafc _PyEval_EvalFrameDefault + 42076
	73  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	74  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	75  python                              0x0000000100a6ed67 call_function + 183
	76  python                              0x0000000100a6cb8d _PyEval_EvalFrameDefault + 46317
	77  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	78  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	79  python                              0x0000000100a6ed67 call_function + 183
	80  python                              0x0000000100a6bafc _PyEval_EvalFrameDefault + 42076
	81  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	82  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	83  python                              0x0000000100a6ed67 call_function + 183
	84  python                              0x0000000100a6bafc _PyEval_EvalFrameDefault + 42076
	85  python                              0x00000001009312d5 function_code_fastcall + 117
	86  python                              0x0000000100a6ed67 call_function + 183
	87  python                              0x0000000100a6bafc _PyEval_EvalFrameDefault + 42076
	88  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	89  python                              0x00000001009307c7 _PyFunction_FastCallDict + 231
	90  python                              0x0000000100934702 method_call + 130
	91  python                              0x0000000100932172 PyObject_Call + 130
	92  python                              0x0000000100a6ccd9 _PyEval_EvalFrameDefault + 46649
	93  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	94  python                              0x0000000100931a03 _PyFunction_FastCallKeywords + 195
	95  python                              0x0000000100a6ed67 call_function + 183
	96  python                              0x0000000100a6cad4 _PyEval_EvalFrameDefault + 46132
	97  python                              0x0000000100a6046e _PyEval_EvalCodeWithName + 414
	98  python                              0x0000000100ac3ce0 PyRun_FileExFlags + 256
	99  python                              0x0000000100ac3157 PyRun_SimpleFileExFlags + 391
	100 python                              0x0000000100af0dc3 pymain_main + 9635
	101 python                              0x0000000100903f2d main + 125
	102 libdyld.dylib                       0x00007fff2032df3d start + 1
	103 ???                                 0x0000000000000002 0x0 + 2
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      ipython
```

**Comment by kadiryaren** [comment]
pip3 install matplotlib==3.3.3

**Comment by oscargus** [comment]
@kadiryaren some context would be appreciated with your comment.

**Comment by 05e** [comment]
still getting this error. I'm also on MacOS and running the latest version of matplotlib & numpy, but running `plt.show()` at any point in my code causes a segmentation error.
