### ISSUE TITLE
[ENH]: Starting point/offset for (logarithmic and/or relative) bar plots

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#27951]
### Problem

I would like to create a figure similar to this:

![image](https://github.com/matplotlib/matplotlib/assets/8114497/a0f22863-5381-4c3b-9b75-53e3a6cdee73)

where the bars starts with a given offset (in this case 1).

Clearly it can be achieved with a bit of tricks, but I would prefer if one can simply provide an offset argument to bar. For example, I am now not using a logarithmic scale (and therefore there are no logarithmic minor ticks), but rather compute the log and then hard-code the y-labels.

I imagine a similar situation where one would like the bars to start at a given value and not having a log-scale, like in relative bars.

Maybe this can be done in a better way?

(I originally thought the "bottom" argument would solve this, but after testing and reading the doc-string properly, it is clear that it solves another problem.)

### Proposed solution

Add an offset argument that behaves as a reference for the bar plots.

(Or provide an example where the same effect is obtained.)

**Comment by ksunden** [comment]
The fundamental problem here is that bar is parameterized by the *height* of the bar, and not the position of the top of the bar... 

so I'm not sure an offset really helps here.... 

I think on a linear scale bottom is exactly what you want, but you need a negative height to get a bar to go down, and that just doesn't really work with log scale.

There are certainly a few trick you could play with transforms and such, but yeah, dealing with negative numbers on log scales is tricky, and I don't think it is solved by an offset.

**Comment by tacaswell** [comment]
I don't quite understand why `bottom` does not solve this problem (or at least `ax.bar(x, hegiht-b, bottom=b)`?

```python
import matplotlib.pyplot as plt
plt.bar(range(6), [-.5, 10, 100, 1000, 1, -.99], bottom=1)
plt.yscale('log')
```

![so](https://github.com/matplotlib/matplotlib/assets/199813/c93aa0bd-c75a-4ef3-91c0-61cd34519ea4)

**Comment by oscargus** [comment]
> I don't quite understand why bottom does not solve this problem (or at least ax.bar(x, hegiht-b, bottom=b)?

Me neither. Thanks!

I'll try to see if I can find an example that does something similar or if I should add one. Will close if found.

(Just looking at the thumbnails at the bar page didn't really give any interesting examples, but there may still be one.)
