### ISSUE TITLE
[Doc]: Improve contribute instructions

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#28005]
### Documentation Link

https://matplotlib.org/devdocs/devel/index.html

### Problem / Suggested improvement

* [x] Check section order and hierarchy. E.g.
  https://matplotlib.org/devdocs/devel/contribute.html#good-first-issues And
  https://matplotlib.org/devdocs/devel/contribute.html#work-on-an-issue
  Are subsections in „get connected“

* [x] https://matplotlib.org/devdocs/devel/contribute.html#work-on-an-issue should be written more with absolute newcomers in mind.
  * write out the term pull request on first use, instead of only using PR.
  * instead of just „ check if there is an existing PR“ mention how I.e. that PRs are linked in the issue.
  * „ If you have opened such a PR, please comment on the issue thread to avoid duplication of work.“ Linking via „closes #…“ is more appropriate. But maybe this should be left out here completely and instead be part of https://matplotlib.org/devdocs/devel/contribute.html#open-a-pull-request-on-matplotlib and/or https://matplotlib.org/devdocs/devel/development_workflow.html#open-a-pull-request

**Comment by timhoffm** [comment]
> Generally I've been working on the assumption that contribute.rst is the guide for absolute beginners, and devolpment_workflow.rst is for more experienced folks, so hopefully written slightly differently for both.

I‘d rather phrase this as: contribute.rst is the fist point of contact and a high-level overview directing people to the more detailed instuctions, and development_workflow.rst is one such instruction.

**Comment by Impaler343** [comment]
I dont know if this is being fixed in this Issue, but all of the links in this pic lead to the top of the Contribute page, while they should be leading to different sections of the page. But the URLs they lead to are all different
<img width="348" alt="image" src="https://github.com/matplotlib/matplotlib/assets/73378019/6ae4401b-921a-4516-8da4-b6b6e931a4dd">

**Comment by Impaler343** [comment]
> > I dont know if this is being fixed in this Issue, but all of the links in this pic lead to the top of the Contribute page, while they should be leading to different sections of the page. But the URLs they lead to are all different
> 
> I can't replicate this, so which browser are you on and which version of the docs?

Doc version - 3.8.4, 3.8.3
Browser - Google Chrome, Firefox, Edge
On mobile as well. I search for "matplotlib documentation" --> click on the first link --> Click on Contribute under the Contribute section --> Click on one of the links

**Comment by timhoffm** [comment]
> -> click on the first link -->

Please post this link.

**Comment by rcomer** [comment]
In iOS, if I "open in background" (equivalent to open in new tab in most browsers) the link always takes me to the top of the page.  Are you doing something like that @Impaler343?

**Comment by timhoffm** [comment]
@rcomer What is the link target? If it is correct, IMHO then the browser is acting funny and we cannot do anything about it.

**Comment by rcomer** [comment]
Yes, I always assumed this was a browser issue.  If I just click the link, I get to the right place.

**Comment by timhoffm** [comment]
Fixed by PRs #28011, #28024, #28026.

The link discussion is OT and a browser issue that we cannot do anything about.

**Comment by Impaler343** [comment]
> > -> click on the first link -->
> 
> Please post this link.

https://matplotlib.org/stable/devel/index.html
![IMG_20240407_040529](https://github.com/matplotlib/matplotlib/assets/73378019/27ebb04b-194b-44f9-8c60-0d33825035bf)

**Comment by Impaler343** [comment]
> Fixed by PRs #28011, #28024, #28026.
> 
> The link discussion is OT and a browser issue that we cannot do anything about.

Hmmmmm I wonder why all of my browsers are acting funny

**Comment by Impaler343** [comment]
> In iOS Safari, if I "open in background" (equivalent to open in new tab in most browsers) the link always takes me to the top of the page. Are you doing something like that @Impaler343?

I don't have Safari but when I try to open in a new tab, I the problem still persists

**Comment by Impaler343** [comment]
> Ugh still can't replicate :/ have you cleared/ can you clear your cache?

Just tried this, didn't work 🥲

**Comment by Impaler343** [comment]
> > > Fixed by PRs #28011, #28024, #28026.
> > > The link discussion is OT and a browser issue that we cannot do anything about.
> > 
> > 
> > Hmmmmm I wonder why all of my browsers are acting funny. I even tried on a couple of my friends' browsers
> 
> Can you take a screen cast to show us?


https://github.com/matplotlib/matplotlib/assets/73378019/edf5310f-caa7-4341-af51-68634e9240b8

**Comment by Impaler343** [comment]
> In iOS Safari, if I "open in background" (equivalent to open in new tab in most browsers) the link always takes me to the top of the page. Are you doing something like that @Impaler343?

Just checked and works well on safari, must be a browser issue on all the other ones

**Comment by Impaler343** [comment]
> > In iOS Safari, if I "open in background" (equivalent to open in new tab in most browsers) the link always takes me to the top of the page. Are you doing something like that @Impaler343?
> 
> Just checked and works well on safari, must be a browser issue on all the other ones

The new tab method works on chrome and not on mobile

**Comment by Impaler343** [comment]
> > > In iOS Safari, if I "open in background" (equivalent to open in new tab in most browsers) the link always takes me to the top of the page. Are you doing something like that @Impaler343?
> > 
> > 
> > Just checked and works well on safari, must be a browser issue on all the other ones
> 
> The new tab method on chrome, firefox and edge works on destop and not on mobile
