### ISSUE TITLE
Remove spacing between polygons

### ISSUE THREAD

**Issue by letmaik** [matplotlib/matplotlib#2823]
![test image](https://f.cloud.github.com/assets/530988/2216573/1a9f9448-9a0d-11e3-8288-d4c37dbefc92.png)

I believe the spacing between the polygons shouldn't be there. Below is my code. Is this a bug or am I missing some option? It happens on all backends. 

I know that I can enlarge the polygons slightly so that they overlap each other which then removes these spaces, but this approach is only suitable for very simple polygons like the rectangular ones above, and in my real use-case I have arbitrarily shaped polygons, so that's not really an option.

``` python
import numpy as np

import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection

def createPolygons(xv, yv):
    assert xv.shape == yv.shape
    xy = np.dstack((xv,yv))

    # adapted from matplotlib.collections.QuadMesh.convert_mesh_to_paths
    verts = np.concatenate((
                xy[0:-1, 0:-1],
                xy[0:-1, 1:  ],
                xy[1:  , 1:  ],
                xy[1:  , 0:-1],
                ), axis=2)
    verts = verts.reshape((xv.shape[0]-1) * (xv.shape[1]-1), 4, 2)

    return verts

def drawPlot(verts, outputFile, blackbg, widthPx):
    if blackbg:
        mpl.rcParams['savefig.facecolor'] = 'black'
    else:
        mpl.rcParams['savefig.facecolor'] = 'white'

    ax = plt.gca()
    fig = plt.gcf()

    if blackbg:
        fig.patch.set_facecolor('black')
        ax.patch.set_facecolor('black')
        ax.spines['bottom'].set_color('white')
        ax.spines['top'].set_color('white')
        ax.spines['left'].set_color('white')
        ax.spines['right'].set_color('white')
        for i in ax.get_xticklabels(): i.set_color("white")
        for i in ax.get_yticklabels(): i.set_color("white")
        for t in ax.xaxis.get_ticklines(): t.set_color('white')
        for t in ax.yaxis.get_ticklines(): t.set_color('white')
        ax.xaxis.label.set_color('white')
        ax.yaxis.label.set_color('white')

    coll = PolyCollection(verts, facecolors=None, edgecolors='none')

    ax.add_collection(coll)
    ax.autoscale()

    width = fig.get_figwidth()
    dpi = widthPx / width

    fig.savefig(outputFile, dpi=dpi)
    plt.close(fig)


x = np.linspace(0, 10, num=10)
xv, yv = np.meshgrid(x, x)
verts = createPolygons(xv, yv)
drawPlot(verts, 'test.png', blackbg=True, widthPx=500)
```

**Comment by pelson** [comment]
I just tried the attached code on master and did not see the issue that was reported. I therefore think this is now resolved.

@tacaswell wrote:
> I think this should be left open (or at a minimum replaced) as a feature request for a way to pass in an arbitrary mesh + colors. That is why I punted to 1.5.

This hasn't been done AFAIK, but should definitely be a separate issue if it does *actually* need to be tracked (I'm sceptical).


Finally, I think the original question was perhaps a little contrived? If one really wanted to use a bunch of polygons to represent an image you might consider using a pcolormesh. An example of a curved pcolormesh is here (I'm showing it without data to highlight that there are no unsightly borders):

```
import matplotlib.pyplot as plt
import numpy as np


θ, r = np.meshgrid(np.linspace(0, np.pi, 15), np.linspace(1, 5, 10))
verts = np.stack([np.sin(θ)*r, np.cos(θ)*r], axis=-1)
cmap = plt.get_cmap('Reds')

c = cmap(verts[:, :, 0].flatten()/verts[:, :, 0].max())
plt.pcolormesh(verts[:, :, 0], verts[:, :, 1],
               np.ones(verts[:-1, :-1, 0].shape))

plt.show()
```
![figure_1](https://user-images.githubusercontent.com/810663/50288556-325e7980-045e-11e9-8bc5-4c37d663b7d4.png)

Yet another alternative is to use a library that does the image transformation for you - cartopy has an example of doing this at https://scitools.org.uk/cartopy/docs/latest/gallery/geostationary.html#sphx-glr-gallery-geostationary-py.

Whilst I have the power to close the issue, I'm resisting given the suggestion from @tacaswell. I'll leave it to him to make the final call.

**Comment by anntzer** [comment]
PolyCollections are basically bound to always have this problem; drawing a quadmesh is indeed the way to go.

On the other hand, perhaps this suggests that what's needed is a way for PolyCollections to convert themselves to QuadMeshes (triangulating ("quadrangulating"?) larger polygons on-demand -- that's the "interesting" part) for drawing?

**Comment by raphaelquast** [comment]
any updates on this?
I'm experiencing similar problems when plotting a collection of ~100K polygons.  
Using `coll.set_edgecolors(coll.get_facecolors())` and a linewidth according to the zoom seems to solve the problem on my side but I'd very much prefer a general solution that does not need manual tweaking of linewidths...

**Comment by WeatherGod** [comment]
There is an experimental backend that might address this problem that you
could try out: https://github.com/matplotlib/mplcairo

**Comment by raphaelquast** [comment]
hey @WeatherGod, thanks for the suggestion!  
I gave it a quick try, and it seems to work nice and really fast.  
Unfortunately the spacing of the PolygonCollection is still present...

For now, I found that converting the `PolygonCollection` into a `TriMesh` (e.g. by simply dividing each rectangle in the diagonal) 
can be used to create the desired (edge-free) appearance...

**Comment by QuLogic** [comment]
Closing as a duplicate of #1188
