### ISSUE TITLE
[Bug]: matplotlib (kiwisolver) interference with other package

### ISSUE THREAD

**Issue by mrrezaie** [matplotlib/matplotlib#28991]
### Bug summary

Hi, I use another package (opensim), which has lots of dll and exe files, along with matplotlib. It seems that matplotlib is broking something at import.

### Actual outcome

If I import matplotlib first, I receive this error:
```python
In [1]: import matplotlib
In [2]: import opensim
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d100d6ac66f2> in ?()
----> 1 import opensim

F:\Python312\Lib\site-packages\opensim\__init__.py in ?()
     16 #     if (os.path.exists(dev_path)):
     17 #         os.add_dll_directory(dev_path)
     18
     19 from .simbody import *
---> 20 from .common import *
     21 from .simulation import *
     22 from .actuators import *
     23 from .analyses import *

F:\Python312\Lib\site-packages\opensim\common.py in ?()
      6
      7 from sys import version_info as _swig_python_version_info
      8 # Import the low-level C/C++ module
      9 if __package__ or "." in __name__:
---> 10     from . import _common
     11 else:
     12     import _common
     13

ImportError: DLL load failed while importing _common: A dynamic link library (DLL) initialization routine failed.
```

### Expected outcome

If I import opensim, followed by matplotlib, everything works well:
```python
In [1]: import opensim
In [2]: import matplotlib
In [3]: 
```
### Operating system

Windows 11

### Matplotlib Version

3.9.2

### Python version

3.12.7

### Installation

pip

**Comment by tacaswell** [comment]
How did you install opensim?  It does not look like it is on pypi and their docs reccomend using conda (https://opensimconfluence.atlassian.net/wiki/spaces/OpenSim/pages/53085346/Scripting+in+Python).

While wheels _mostly_ work, there are some technical and inter-project coordination issues where they will fail with extension modules (see https://pypackaging-native.github.io for more details).  In the short term I suggest sticking with conda or pixi (https://pixi.sh/latest/) for creating your environments and steer clear of wheels.

My suspicion is that both libraries are built against and bundle different versions of a shared dependency (which wheels require us to do), likely the c++ runtime, with the condition that the code built against the older version can run with the newer version of the library, but code built against the newer version can not run with the older.  Based on the order that works, I think this means that mpl is built with the older version and opensim is built with the newer version.

I suspect that this is a relative of https://github.com/matplotlib/matplotlib/issues/28551

----

In the future, please always copy-paste error messages rather than screen shots.  Text is much easier to deal with and while not super relevant here, if someone wants to try to reproduce

**Comment by jklymak** [comment]
Have you opened an issue with Opensim?   It is their library that can't load.

**Comment by mrrezaie** [comment]
Thanks @tacaswell and @jklymak for your responses.

> Have you opened an issue with Opensim? It is their library that can't load.

OpenSim actually works well, even if I import it after numpy, scipy, or scikit-learn. But, in this specific condition the error is raised.

> In the future, please always copy-paste error messages rather than screen shots. Text is much easier to deal with and while not super relevant here, if someone wants to try to reproduce.

Sorry, I just changed the errors to text.

> How did you install opensim?

I built opensim-core for win64 and py3.12 using Visual Studio 17 2022. Do you think the version of MSVC is the issue?

I investigated more and checked the imported modules using `sys.modules`, the `kiwisolver` package is actually the reason of that failure. Any idea on this?

Any help is greatly appreciated.

**Comment by jklymak** [comment]
You probably need to build all the packages with c extensions the same way. Or install everything with conda/mamba if that is available.

**Comment by mrrezaie** [comment]
I see that many users have opened similar issue, but this is not matplotlib-specific. Is kiwisolver a required dependency? What are the limitations without kiwisolver? I could see that it has vey limited application in matplotlib, only here:
https://github.com/matplotlib/matplotlib/blob/3f42f3591b04978184bafe31ba84696088117649/lib/matplotlib/_layoutgrid.py#L20

By any chance, would it be possible to make it optional? So, no one would ever open any issue related to DLL ImportError.

**Comment by jklymak** [comment]
It's used for the constrained layout manager.  We don't currently have optional dependencies and I'm not sure how easy it is to make something optional.  Many of our examples use constrained layout so making it optional would mean we would have to rework all of those.  

But I'm not very familiar with windows packaging. Is there some reason we/kiwisolver/our users cannot fix this?

**Comment by tacaswell** [comment]
```
pip install --no-binary kiwisolver kiwisolver
```

will avoid using the kiwisolver wheels and compile it from source.  I suspect that will solve the problem for @mrrezaie (not using pip/wheel and using conda/mamba/pixi instead is a more general solution).

I suspect (but am not 100% sure) that there is a technical path to making this work with wheels in general (it may require a one or more no-change "releases" to rebuild wheels), but issues stemming from packaging issues with one of the many distribution channels is not sufficient reason to make it an optional dependency.

**Comment by jklymak** [comment]
I do wonder if we should consider vendoring kiwisolver so if there are build problems they will be for all of Matplotlib and not just in a dependency.  I also am not sure how kiwisolver feels about the added maintenance burden of supporting our very broad user base; maybe @MatthieuDartiailh has an opinion?

**Comment by mrrezaie** [comment]
Hi, thanks for your help. The `pip install --no-binary` command didn't help, and the same error was raised (hope I did it correctly). 

I found [this post](https://github.com/nucleic/kiwi/issues/173#issuecomment-1819662678) (related to matplotlib and kiwisolver), and installed [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), it fixed the issue completely!!! Just curious, is there any integration? For example, `pip install kiwisolver` could detect the os and install an appropriate vc_redist afterwards. This would avoid lots of headaches :)

**Comment by QuLogic** [comment]
kiwisolver applied the same fix we did: https://github.com/nucleic/kiwi/pull/183/commits/76955978a70681fae555365f40769258f5d78553 but you must be using the latest version.

As this has been fixed there, I don't think we should do much else ourselves.

**Comment by MatthieuDartiailh** [comment]
I am fine with doing whatever update help streamline the process as I did following the suggestion from @QuLogic.

Side note, as a user of matplotlib I very much enjoy the constraints based layout and wished it was the default so I am happy to help make kiwi integration easier.

**Comment by jklymak** [comment]
Thanks @MatthieuDartiailh awesome - as long as we aren't imposing on you we are more than happy to _not_ vendor Kiwisolver.  Just wanted to make sure it wasn't an unintended obligation on your part :wink:  Thanks for maintaining it, as it is a very nice abstraction of some difficult concepts.

**Comment by mrrezaie** [comment]
Thanks all, please let me continue this discussion here a little bit further. 

Any idea why `pip install kiwisolver --no-binary kiwisolver` didn't fix the issue? I [did this](https://github.com/mrrezaie/testBuildKiwisolver/blob/cc951f5c11b80bd5d33e6ec91e828e7cb40ce593/.github/workflows/build_kiwisolver.yml#L57) and [built opensim](https://github.com/mrrezaie/testBuildOpenSim/blob/eb30eba688c32f902100b0e2bdca36ab61f68676/.github/workflows/build_opensim-core.yml#L123) in GitHub Actions windows-2022 runner which has [Visual Studio Enterprise 2022](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#visual-studio-enterprise-2022) by default, then downloaded the wheel files for local installation.

@MatthieuDartiailh 
And, if installing the [Microsoft Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) is a permanent solution for non-developers and non-conda users like me, would it be possible to guide users during installation? For example, a simple warning after kiwisolver [pip] installation that _the incompatibilities between packages could be resolved by installing Microsoft Visual C++ Redistributable_, followed by the link to the download page.

Thanks.

**Comment by jklymak** [comment]
@mrrezaie if you are still having problems installing Kiwisolver, and you are using the latest version of kiwisolver, then perhaps the place to discuss is on the kwiwsolver issue tracker.  Per the above, we think this issue was solved in the latest release.  

If you are not a developer, I strongly suggest using conda/mamba for installing things that require compilation, particularly for windows, particularly if there is no wheel available for opens.    Then you get the benefit of folks having already done this for you (assuming you have a supported machine).

**Comment by mrrezaie** [comment]
> we think this issue was solved in the latest release.

The latest version is 1.4.7 (https://pypi.org/project/kiwisolver/) since Sep 4 and at the time of opening this issue. 

Anyway, thank again.
