### ISSUE TITLE
Figures in the notebook backend are too large following DPI changes

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#5945]
The changes to the figure dpi in a90331506713c6be3d9e1a866d63a34df05d8dfc makes the figure in the notebook backend larger and more fuzzy. Presumably because the size of the figure is not set correctly in the nbagg backend and the figure ends up being rescaled to the same default display dpi

Edit:

The actual issue is just that the figures are now larger because we increased the DPI. 
The actual figure size in the notebook is in pixels so that the figure size in pixels will be dpi * figsize_in_inches exactly as is should be however the figure is subjectively to large

**Comment by jenshnielsen** [comment]
On 1.5.1
![screen shot 2016-01-29 at 15 14 45](https://cloud.githubusercontent.com/assets/548266/12679262/14fdeac8-c69b-11e5-9600-15cacfa40f0f.png)

On 2.x 

![screen shot 2016-01-29 at 15 13 51](https://cloud.githubusercontent.com/assets/548266/12679244/f73b0bec-c69a-11e5-8706-bc656fd51c74.png)

I bisected the change to a903315 as indicated above

**Comment by jenshnielsen** [comment]
Thinking a bit more about this it seems like the issue is that the figure size depends on the DPI of the image generated which is should not.

**Comment by mdboom** [comment]
I'm not seeing the fuzzyness in the second image.  One would expect the image to be larger when increasing the DPI -- since figure size comes not from the notebook, but from a hard coded default in inches from matplotlibrc.

That said, I think we need to get better about communicating the best size from the notebook to matplotlib, which would resolve this issue.  I don't recall if that's one of the things fixed by #5754 or not...

**Comment by jenshnielsen** [comment]
You are right of cause. The only thing that determines the figure size on screen is the number of pixels in the png which grows with dpi change. 

That being said I still think the default figure size is way to large for the notebook now.

And I still see the fuzzyness. 

Compare 

1.5.1

![matplotlib 151](https://cloud.githubusercontent.com/assets/548266/12681756/17d9b29c-c6a8-11e5-9390-bc19ff018a80.png)

2.x 

![matplotlib 2x](https://cloud.githubusercontent.com/assets/548266/12681759/1c6126b0-c6a8-11e5-8ad0-5623853ba8ba.png)

2.x with dpi 80

![matplotlib 2x dpi80](https://cloud.githubusercontent.com/assets/548266/12681763/23c4effe-c6a8-11e5-8bcd-64bb19164d04.png)


I have scaled the figure size in these examples to create a figure with both the old and the new size by multiplying with 10/8 and 8/10 respectively

**Comment by efiring** [comment]
Is it possible for the notebook backend to ask the browser what it thinks the actual screen dpi is?

**Comment by mdboom** [comment]
I don't think so -- the best you get is whether the browser is in "retina mode" (scaling) or not.  But you can get the width of the cell, or the width of the document frame, which while not the same thing would allow us to shrink the figure accordingly to fit.

**Comment by jenshnielsen** [comment]
closed by #6290
