### ISSUE TITLE
Transparency, color mixing, gamma & linear color space ?

### ISSUE THREAD

**Issue by gvinterhalter** [matplotlib/matplotlib#5949]
Hello all.

This is my first time playing with matplotlib so I'm not sure if this is a feature or a bug but I needed to scatter a large number of points that are transparent. I need transparency so that I could observe the density of theses particles (I should probably make a 2D histogram... ). The problem I noticed is that if I increased the alpha of particles I would start to see black. The picture explains it.

![problem](https://cloud.githubusercontent.com/assets/6205969/12699436/2f481e32-c7bb-11e5-9003-d23229f51d59.png)

I believe the problem is the handling of colors internally. Is it all linear color space with correct gamma handling ?

**Comment by WeatherGod** [comment]
There is work going on to improve image interpolation. I think that covers
some blending. We should probably make sure of that.

As for your situation, though, use hexbin(). It is designed for these sorts
of plots.

**Comment by tacaswell** [comment]
Currently we do blending in uint8 RGBA buffers, to support this we would need to move to doing the blending in float buffers.  This will involved a good deal of c++ work in the AGG layer and possibly work with the upstream Agg project.

**Comment by gvinterhalter** [comment]
Maybe this can help
https://sourceforge.net/p/vector-agg/mailman/vector-agg-general/thread/D15DE8FE767142738F1879DE856244F5@gmail.com/

**Comment by tacaswell** [comment]
@mdboom Has reported (more or less) that the Agg folks claim this should work, but when he tried it (recently) it did not work as advertised.  I am not sure where the branch he was working on is though.

**Comment by QuLogic** [comment]
This was fixed by #5718.

**Comment by tacaswell** [comment]
@QuLogic I do not understand how this was fixed.

**Comment by QuLogic** [comment]
I'd defer to @mdboom because #5718 is a pretty big PR and I don't quite follow all of it, but the example you gave in the first post works on `v2.x` all the way back until the backport of #5718, before which it exhibits the old behaviour.

**Comment by QuLogic** [comment]
Err, wait, this might be the wrong issue actually? Let me double-check.

**Comment by QuLogic** [comment]
Yep, sorry for the noise. My tabs got crossed somehow and I meant to ask @gvinterhalter for a small example, but in the meantime I've written one myself:
```python
import numpy as np
matplotlib.pyplot as plt

np.random.seed(1)
x = np.random.randn(100000)
y = np.random.randn(100000)

plt.plot(x, y, 'o', markerfacecolor='m', markeredgecolor='none', alpha=0.005)
plt.show()
```
which is naturally still broken on `v2.x`:
![figure_1](https://cloud.githubusercontent.com/assets/302469/18981063/b4bfe994-86a8-11e6-8a17-601556a3d26e.png)

**Comment by sjvrijn** [comment]
Can confirm that [the above example ](https://github.com/matplotlib/matplotlib/issues/5949#issuecomment-250658658) still produces the same output in version 3.0.1

**Comment by jklymak** [comment]
Does this work in pml-cairo?

**Comment by jklymak** [comment]
... no, it actually is more pronounced I think...

**Comment by anntzer** [comment]
It works if you use `mplcairo.set_option(float_surface=True)` (which is basically exactly what this PR asks for)... but you need to be using cairo master for that :-)
