### ISSUE TITLE
Exception on font caching

### ISSUE THREAD

**Issue by gbrand-salesforce** [matplotlib/matplotlib#8653]
### Bug report

**Bug summary**

On importing matplotlib.pylab for the first time, I get the following exception raised from functools32:

> TypeError: Cannot cache mutable collections - use tuple/frozenset instead !!! 

**Code for reproduction**

```python
import matplotlib.pylab
```

**Actual outcome**

```
TypeErrorTraceback (most recent call last)
<ipython-input-9-b45c70310bd1> in <module>()
      5 import numpy
      6 import matplotlib
----> 7 import matplotlib.pylab
      8 get_ipython().magic(u'matplotlib inline')
      9 import datetime

/usr/local/lib/python2.7/dist-packages/matplotlib/pylab.py in <module>()
    255     window_hanning, window_none)
    256 
--> 257 from matplotlib import cbook, mlab, pyplot as plt
    258 from matplotlib.pyplot import *
    259 

/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

/usr/local/lib/python2.7/dist-packages/matplotlib/colorbar.py in <module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

/usr/local/lib/python2.7/dist-packages/matplotlib/contour.py in <module>()
     20 import matplotlib.colors as colors
     21 import matplotlib.collections as mcoll
---> 22 import matplotlib.font_manager as font_manager
     23 import matplotlib.text as text
     24 import matplotlib.cbook as cbook

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py in <module>()
   1437             raise
   1438         except:
-> 1439             _rebuild()
   1440     else:
   1441         _rebuild()

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py in _rebuild()
   1416         global fontManager
   1417 
-> 1418         fontManager = FontManager()
   1419 
   1420         if _fmcache:

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py in __init__(self, size, weight)
   1051         #  Load TrueType fonts and create font dictionary.
   1052 
-> 1053         self.ttffiles = findSystemFonts(paths) + findSystemFonts()
   1054         self.defaultFamily = {
   1055             'ttf': 'DejaVu Sans',

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py in findSystemFonts(fontpaths, fontext)
    334                     fontfiles.add(f)
    335 
--> 336             for f in get_fontconfig_fonts(fontext):
    337                 fontfiles.add(f)
    338 

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py in get_fontconfig_fonts(fontext)
    301     """
    302     fontext = get_fontext_synonyms(fontext)
--> 303     return [fname for fname in _call_fc_list()
    304             if os.path.splitext(fname)[1][1:] in fontext]
    305 

/app/trdpty/functools32/functools32.pyc in wrapper(*args, **kwds)
    419                 #We do not allow caching of mutable collections
    420                 if isinstance(result, (list, set)):
--> 421                     raise TypeError('Cannot cache mutable collections - use tuple/frozenset instead !!!')
    422 
    423 #TODO: Enable if multithreading support is required, instead of the same block unindented

TypeError: Cannot cache mutable collections - use tuple/frozenset instead !!!

```

**Matplotlib version**

  * Operating System: Ubuntu 16.04 
  * Matplotlib Version: 2.0.0
  * Python Version: 2.7.12
  * Jupyter Version: notebook version 5.0.0, IPython version 5.1.0

Installation:

pip install functools32==3.2.3.post2
pip install numpy==1.10.4
pip install scipy==0.17.0
pip install ipykernel==4.6.1
pip install jupyter==1.0.0
pip install jupyter-client==4.4.0
pip install jupyter-console==5.0.0
pip install jupyter-core==4.2.0
pip install matplotlib==2.0.0
pip install ipython==5.1.0

**Comment by jenshnielsen** [comment]
I think this is resolved in matplotlib 2.0.2 or perhaps even 2.0.1. The issue is that the output returned from fc list was being incorrectly concatenated into a string

**Comment by anntzer** [comment]
What is your version of functools32?  I cannot find the error message you mention in the functools32 codebase or git history.

**Comment by gbrand-salesforce** [comment]
functools32 is version 3.2.3.post2

**Comment by gbrand-salesforce** [comment]
Updated to matplotlib 2.0.2 - and I still get the same error...

**Comment by jenshnielsen** [comment]
Thats strange, I cant find that line either in functools32. I noticed that it seems like functools32 is not imported from your installed packages. Is it possible that you are not using the installed version but a local copy. Your traceback has ```/app/trdpty/functools32/functools32.pyc``` as the location of functools32

**Comment by anntzer** [comment]
try:
pip uninstall functools32
pip install --upgrade functools32

**Comment by gbrand-salesforce** [comment]
@jenshnielsen You're right, it's the fault of this custom functools32 in 3rdpty. 

Renaming it to not collide with the global functools32 should solve it.
