### ISSUE TITLE
matplotlib spline adjustment changes tick label visibility

### ISSUE THREAD

**Issue by austinbes** [matplotlib/matplotlib#9635]
### Bug report

When adjusting the top spline position of a shared x-axis subplot, the ticks on the subplots axis acquire labels.

**Code for reproduction**

```python
#! /usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 100)
y = 2 * np.sin(x)

fig, (ax0, ax1) = plt.subplots(nrows = 2, sharex=True)

ax0.plot(x, y)
ax1.plot(x, y)

ax0.spines['top'].set_position(('outward', 0))

plt.show()
```

**Actual outcome**

![Top subplot ticks have labels](https://i.imgur.com/VoJ2Lk9.png)

**Expected outcome**

![Top subplot ticks have no labels](https://i.imgur.com/9QJAPkb.png)

Note that the "expected outcome" is the same script, run with the `ax0.spines...` line commented out

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: 2.0.0 (via `pip`)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5.2
  * Jupyter version (if applicable): n/a
  * Other libraries: 
      * `numpy`: 1.12.0

**Comment by afvincent** [comment]
@austinbes Thank you for the comprehensive bug report :). Would it be possible to test Matplotlib 2.1.0? I just tried your MWE with the current master branch as well as with the conda version of Matplotlib 2.1.0: I get plots like your second one (“expected outcome”), so it may have been already fixed.

**Comment by austinbes** [comment]
My MWE works as you say now -- but I still get the unexpected result with the more complex formatting from which I discovered this issue originally.

I'll try to pare it down again with the new version and see what I come up with (probably in the next couple days)

**Comment by austinbes** [comment]
Ah, looks like a mistake on my part. Thanks for the help!

**Comment by afvincent** [comment]
`git bisect` seems to indicates that it was fixed in 2348584, which looks plausible to me after a quick glance at the patch.

@austinbes If everything is OK on your with Matplotlib 2.1.0, can we close the isssue?

**Comment by austinbes** [comment]
Yup! It seems quite fixed.
