### ISSUE TITLE
scrolling in plot crashes matplotlib

### ISSUE THREAD

**Issue by samuela** [matplotlib/matplotlib#9637]
### Bug report

**Bug summary**

Scrolling in a figure window crashes matplotlib.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

plt.figure()
plt.show()
```

Run the code and try scrolling down a bunch within the window.

**Actual outcome**

```
Traceback (most recent call last):
  File "matplotlib_scroll_bug.py", line 5, in <module>
    plt.show()
  File "/Users/myusername/Development/sharklasers/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "/Users/myusername/Development/sharklasers/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 193, in __call__
    self.mainloop()
  File "/Users/myusername/Development/sharklasers/venv/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 71, in mainloop
    Tk.mainloop()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 557, in mainloop
    _default_root.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Expected outcome**

Not crashing.

**Matplotlib version**

  * Operating system: macOS 10.12.6
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.2
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Installed via pip.

**Comment by tacaswell** [comment]
Does this persist in 2.1?

**Comment by jklymak** [comment]
If it were me I’d reinstall matplotlib with Conda and see if this is still a problem.  Given that you have two reports of issues w tkagg I somewhat suspect your tk library is old and or broken.

**Comment by samuela** [comment]
@jklymak ah, that could be... i'll look into it

**Comment by samuela** [comment]
@tacaswell Yes, it persists as of 2.1.0.

**Comment by samuela** [comment]
@jklymak 

```
$ tclsh
% puts $tcl_version
8.5
% info patchlevel
8.5.9
% 
```

Is this version supported by matplotlib?

**Comment by tacaswell** [comment]
It also seems to be a Mac specific issue,  

I think the work that needs to be done here is to sort out exactly which versions of tcl/python are problematic together

**Comment by ingwii** [comment]
Is there a solution for this problem?

**Comment by jklymak** [comment]
No.  If you had a reproducible error path that would help...

**Comment by ingwii** [comment]
Can I solve this problem by updating the TkAgg ?

**Comment by boyeborg** [comment]
You can hack the error away with something like this:

```python
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

plt.figure()
plt.plot([1,2,3,4])

while True:
  try:
    plt.show()
  except UnicodeDecodeError:
    continue
  break
```

**Comment by samuela** [comment]
Are there any alternative matplotlib backends on macOS? Working around this looks to be a pain in the butt after reading the discussion on the mailing list.

**Comment by boyeborg** [comment]
A more clean workaround (than what I previously posted) if you just "want it to work" ™, is to write your own show method, like this:

```python
def plt_show():
  try:
    plt.show()
  except UnicodeDecodeError:
    plt_show()
```

And then call `plt_show()` when you want to show the figure. I usually use this just to prevent it from crashing if I accidentally scroll within a figure. If you're writing serious stuff, you should probably find a better solution.

**Comment by evgenyneu** [comment]
I can reproduce it. Crashes reliably for me when I try to scroll over the plot, or use the mouse wheel. Please note that it crashes only when I use 'TkAgg' backend, the default 'MaxOSX' works fine.

  * Operating system: MacOS 10.13.2
  * Matplotlib version: 2.1.2
  * tkinter.TkVersion: 8.5
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.4 

```Python
import matplotlib
matplotlib.use('TkAgg') 
import matplotlib.pyplot as plt

plt.figure()
plt.show()
```

**Comment by efiring** [comment]
I recommend using the qt5agg backend.

**Comment by evgenyneu** [comment]
@efiring thanks I will keep that in mind. However, I'm using the plots in a tkinter app, so 'TkAgg' is my only option, unless I switch to a different GUI library?

**Comment by tacaswell** [comment]
@evgenyneu The exception is coming out of the Tk main loop.  A fix is probably to wrap
https://github.com/matplotlib/matplotlib/blob/0e07bdd529e90280b3676264005fb47ee9ff998d/lib/matplotlib/backends/backend_tkagg.py#L1082-L1084
in a (recursive) `try:...except` block and restart the event loop when this happens, however that is engineering around a bug that is fundamentally in the tk bindings and should be fixed there.

**Comment by evgenyneu** [comment]
Thanks @tacaswell, this try catch workaround works well in my tkinter app. 

> however that is engineering around a bug that is fundamentally in the tk bindings and should be fixed there.

"engineering around", indeed :)

**Comment by nasaWelder** [comment]
I'm still getting this issue while running matplotlib in a tkinter canvas. I found this to be a good solution, instead of recursive calls:

    while True:
        try:
            root.update_idletasks()
            root.update()
        except UnicodeDecodeError:
            print("Caught Scroll Error")

**Comment by nawre** [comment]
Still having the same problem with : 
python 3.7 
OSX 10.13.6 
 TkAgg backend
Crash immediately when scroling in a figure window

**Comment by roykim98** [comment]
Still having this problem with Mac OS 10.14.4 on Python 3.6.5 and 3.7 when using a Pipenv virtual environment and the TkAgg backend. Python is not installed as a framework but instead installed using Pyenv. See a blank figure and scrolling causes it to crash.

**Comment by dalonsoa** [comment]
Hi all, 

The problem seems to be in the version of Python that comes with [Homebrew](https://brew.sh) and that I was using (and I guess you were using, too). 

**If Python is installed from [python.org](https://www.python.org), there is no problem with scrolling**. This seems to be related with the later distributing their own version of Tcl/Tk bundled with the rest of Python. [More information here](https://www.python.org/download/mac/tcltk/). It might work with Anaconda, too, but I haven't tested it.

The details of my system are:
- Python 3.7.4 (from python.org)
- macOS 10.14.6

Cheers!

**Comment by roykim98** [comment]
I can confirm that this is the case, as it works with any full Python framework. Anaconda works as well. Pyenv/Virtual environment instances don't seem to have a backend that cooperate with MPL.

**Comment by tacaswell** [comment]
This is crashing is code that is outside of Matplotlib's control, has anyone who can reproduce this reported it upstream?

**Comment by dsspaceclub** [comment]
> This is crashing is code that is outside of Matplotlib's control, has anyone who can reproduce this reported it upstream?

This crash is 100% reproducible on my Mac. 

```
import numpy as np
import matplotlib.pyplot as plt
N = 50
x = np.random.rand(N)
y = np.random.rand(N)
ax = plt.subplot(projection='3d')
ax.scatter3D(x, y, c=y)
plt.show()
```
What does "upstream" mean?

**Comment by jklymak** [comment]
@dsspaceclub  What backend are you using, and how are you installing?  

I'm not even sure from any of the above what "scrolling" means in the context of a plot.  Do you mean using the scroll wheel to zoom?  Running the above on my anaconda-based python/tk nothing happens if I use the scroll gesture on my trackpad.  But maybe things would be different if I used a scroll wheel.

**Comment by tacaswell** [comment]
The issue here is that in some versions of tk/tkinter + Python tk is not correctly handling the scroll event coming from the operating system (at some level the input from the keyboard/mouse comes in to tk as bytes, I suspect that there are special cases for the mouse button / motion codes and then the rest of the codes are assumed to keystrokes and attempted to be turned into unicode.  In the case of the scroll wheel (which internally the system treats as "just another button") is falling through to the unicode path despite not being a valid unicode value).

https://stackoverflow.com/questions/48085420/python-3-unicode-codec-error-binding-mousewheel-in-tkinter looks like the same issues independent of Matplotlib.  The claim in the answer to that SO question is to upgrade to a version of tk 8.6 or above. 

@dsspaceclub In this case "upstream" would be either Tk itsself or CPython (which owns the bindings), however it seems like the issue is fixed and the solution is to upgrade Tk (or to use a build of Python that is built against an updated version of Tk as I assume you do not want to build Python from source!).

**Comment by dsspaceclub** [comment]
@jklymak Yes, you're right. using the scroll wheel to zoom crashes 100% with anaconda-based Python and TkAgg

**Comment by jklymak** [comment]
Since this happens independently of Matplotlib, I don't think there is anything we can do about it, and tk will have to fix it.  Im going to close, but if someone can reproduce on a tk install that can register mouse-scroll events in a non-matplotlib GUI, they should ask for a re-open.  Thanks!
